# Gemini API配置
gemini:
  api_key: "your-api-key-here"

# ChromaDB配置
chroma_host: "localhost"
chroma_port: 8000
collection_name: "documents"

# 嵌入模型配置
embedding_model: "all-MiniLM-L6-v2"

# 文档处理配置
chunk_size: 500
chunk_overlap: 100