gemini:
  api_key: "your-api-key-here"  # 請替換為您的 Gemini API 金鑰

chroma_host: "localhost"  # ChromaDB 主機地址
chroma_port: 8000        # ChromaDB 端口

collection_name: "documents"  # 文檔集合名稱

# 文本分割設置
chunk_size: 2000      # 文本塊大小
chunk_overlap: 400    # 重疊部分大小

# 嵌入模型設置
embedding_model: "shibing624/text2vec-base-chinese"  # 使用的嵌入模型

# 服務器設置
server:
  host: "0.0.0.0"    # 服務器監聽地址
  port: 8000         # 服務器端口
  admin_password: "your_admin_password"  # 管理員密碼，用於刪除文檔
  similarity_settings:
    default_threshold: 0.7  # 默認相似度閾值（0-1）
    min_threshold: 0.5     # 最小相似度閾值
    max_threshold: 0.95    # 最大相似度閾值
    step: 0.05            # 調整步長

# 文件上傳設置
upload:
  max_file_size: 10485760  # 最大文件大小（bytes），預設 10MB
  allowed_extensions:      # 允許的文件類型
    - .txt
    - .md
    - .doc
    - .docx
    - .pdf 