version: '3.8'
services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./data/chromadb:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false